#!/usr/bin/env bash
# Configuring load balancer with haproxy.

apt-get update
apt-get install -y haproxy

echo "frontend http-in
        bind *:80
        mode http
        default_backend backend-servers

frontend load_balancer
        bind *:80
        mode http
        balance roundrobin
        option httpclose
        option forwardfor
        server 294290-web-01 54.236.44.9:80 check
        server 294290-web-02 3.90.65.191:80 check

backend backend-servers
        server 294290-web-01 54.236.44.9:80 check
        server 294290-web-02 3.90.65.191:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
