#!/usr/bin/env bash
# Stops nginx and fix the container
sudo service nginx stop
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?80) /\180 /' /etc/nginx/sites-enabled/default
sudo service nginx restart
